{% set name = "datarobot" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f89dddf377df7d0f9c059c8cd944db996b4990d195c10c59f8e5a19855b80d76

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - contextlib2 >=0.5.5
    - pandas >=0.15
    - numpy
    - pyyaml >=3.11
    - requests >=2.21
    - requests-toolbelt >=0.6
    - trafaret !=1.1.0,<2.2,>=0.7
    - urllib3 >=1.23
    - typing-extensions ==4.3.0

test:
  imports:
    - datarobot

about:
  home: https://www.datarobot.com/
  license: DataRobot Tool and Utility Agreement
  license_family: PROPRIETARY
  license_file: LICENSE.txt
  summary: This client library is designed to support the DataRobot API.
  description: |
    datarobot is a client library for working with the <https://www.datarobot.com/> platform API.
  doc_url: https://datarobot-public-api-client.readthedocs-hosted.com

extra:
  recipe-maintainers:
    - dsakagi
    - alexalokhinrobot
    - axik
    - mbromanowsky
    - AndrewSonwat
    - ahjota
