{% set name = "datarobot" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8522040da36de19f7b2d1adc1a4e19812d915d3e315d52052b576233c185d98c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - strenum
    - pandas >=0.15
    - numpy
    - pyyaml >=3.11
    - requests >=2.21
    - requests-toolbelt >=0.6
    - trafaret !=1.1.0,<2.2,>=0.7
    - urllib3 >=1.23
    - typing_extensions
    - python-dateutil
    - mypy_extensions
    - pytz

test:
  imports:
    - datarobot

about:
  home: https://www.datarobot.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: This client library is designed to support the DataRobot API.
  description: |
    datarobot is a client library for working with the <https://www.datarobot.com/> platform API.
  doc_url: https://datarobot-public-api-client.readthedocs-hosted.com

extra:
  recipe-maintainers:
    - dsakagi
    - ahjota
